name: CI / Deploy to GHCR

on:
  push:
    tags:
      - '*'
  schedule:
      - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  USERNAME: ${{ github.repository_owner }}
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN || secrets.BOT_TOKEN }}
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Login to the Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Extract Metadatafor Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=pr
            type=edge
          flavor: |
            latest=true 
          labels: |
            org.opencontainers.image.title=auto-issue
            org.opencontainers.image.description=Automated Issue Creator
            org.opencontainers.image.vendor=Vedansh
      - name: Verify Tags and Labels
        run: |
          echo "## Github Action Summary - Docker CI " >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.tags }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.meta.outputs.labels }} " >> $GITHUB_STEP_SUMMARY
          echo "*** VERIFICATION COMPLETED *** "

      - name: Build and Push Image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7