name: CI / Auto Issue Closer
on:
  issues:
    types:
      - opened
concurrency:
  group: ${{ github.event.issue.number }}
jobs:
  delete-test-issues:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'test')
    steps:
      - run: |
          curl --silent --show-error \
            --request PATCH \
            --header "Accept: application/vnd.github.v3+json" \
            --header "Authorization: token ${{ secrets.BOT_TOKEN }}" \
            --url "https://api.github.com/repos/dacbd/create-issue-action/issues/${{ github.event.issue.number }}" \
            --data '{"state":"closed"}'
