name: CI / Tests
on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          npm i; npm run build
  pr-test:
    if: github.event_name == 'pull_request'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        id: new-issue
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN || secrets.BOT_TOKEN }}
          title: "PR test from: `${{ github.ref_name }}`"
          body: |
            # Test
            multiline
          labels: test,automated
          assignees: TheHamsterBot
      - name: View action outputs
        run: |
          echo "${{ steps.new-issue.outputs.NUMBER }}"
          echo "${{ steps.new-issue.outputs.URL }}"
          echo '${{ steps.new-issue.outputs.JSON }}' | jq 
          echo '${{ steps.new-issue.outputs.JSON }}' | jq .state
          echo '${{ steps.new-issue.outputs.JSON }}' | jq .labels[].name
  push-test:
    if: github.event_name == 'push'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  trigger-test:
    if: github.event_name == 'workflow_dispatch' || github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl --silent --show-error \
            --request POST \
            --header "Authorization: token ${{ secrets.GITHUB_TOKEN || secrets.BOT_TOKEN }}" \
            --header "Accept: application/vnd.github.v3+json" \
            --url "https://api.github.com/repos/dacbd/err/dispatches" \
            --data '{"event_type":"basic", "client_payload": {"ref_name":"${{ github.ref_name }}"}}'
